### ISSUE TITLE
<NavvLink>

### ISSUE THREAD

**Issue by stilravi** [jellekitz/Frontend-Applications#5]
https://github.com/jellekitz/Frontend-Applications/blob/adc378022a25a688a4a7428b7910d2f13737dc09/src/App.js#L21

(Optioneel)

Als je <NavLink> gebruikt ipv <Link> zou je eventueel nog een activeClassName kunnen gebruiken als je dat zou willen. Hierdoor kun je makkelijk zien welke link actief is en kan deze makkelijk gestyled worden bijvoorbeeld. (Is maar een optie hoor)

**Comment by jellekitz** [comment]
Maybe next time ;) Thank youuuu
